### PR TITLE
added mod commands and emojify

### PR DESCRIPTION
**Pull request by nexxeln**
### things i added
- slowmode
- timeout (mute)
- set nickname (setnick)
- mass ban
- unban
- emojify (turns text into emojis)

### CODE REVIEW

**Comment by micfun123** [comment]
Me and the other dev will look through this shortly. Can we suggest you join the discord to make talking easier?

**Review by micfun123 — APPROVED** [review]
time out and slow mode is good

**Comment by nexxeln** [comment]
> Me and the other dev will look through this shortly. Can we suggest you join the discord to make talking easier?

sure give me a link

**Comment by micfun123** [comment]
https://discord.gg/uWN4ZM8E

**Comment by micfun123** [comment]
I see two approves so i this will be merged

**Pull request merged**
